version: '3.8'

services:
  # ShopLoc Data Base
  #shoploc-db:
  #image: mysql:latest
  #container_name: shoploc-db
  #environment:
  #- MYSQL_ROOT_PASSWORD=YES
  #- MYSQL_DB=shoploc-db
  #- MYSQL_USER=shoplocU
  #- MYSQL_PASSWORD=YES

  #ports:
  #- "3306:3306"
  #volumes:
  #- ./mysql-data:/var/lib/mysql


  # ShopLoc Back End API
  shoploc-be:
    build: .
    image: shoploc-be
    container_name: shoploc-be
    ports:
      - '8080:8080'
    #depends_on:
     # - shoploc-db

