name: Build and dush docker image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub authentication
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u $DOCKER_USER -p DOCKER_PASSWORD

      - name: Build the docker image
        run: docker build . file Dockerfile --tag

      - name: Push the docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ app


